# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: hsl(185, 100%, 92%);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.ErrorDialogLabel = QtWidgets.QLabel(Dialog)
        self.ErrorDialogLabel.setStyleSheet("border: 2px solid hsl(185, 50%, 85%);")
        self.ErrorDialogLabel.setObjectName("ErrorDialogLabel")
        self.verticalLayout.addWidget(self.ErrorDialogLabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.CloseDialogButton = QtWidgets.QPushButton(Dialog)
        self.CloseDialogButton.setStyleSheet("\n"
"QPushButton {\n"
"    border: 3px solid hsl(185, 50%, 55%);\n"
"    background-color: hsl(185, 100%, 75%);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color : hsl(185, 100%, 45%);\n"
"    border: 3p solid hsl(185 ,50%, 15%);\n"
"}")
        self.CloseDialogButton.setObjectName("CloseDialogButton")
        self.verticalLayout.addWidget(self.CloseDialogButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ErrorDialogLabel.setText(_translate("Dialog", "Error! There are no planes with these characteristics in the database"))
        self.CloseDialogButton.setText(_translate("Dialog", "Close dialog"))
